CREATE TABLE [dbo].[HISTORY]
(
	[COATQUANTITY] INT NOT NULL , 
    [COATTIME] TIME NOT NULL, 
    [USER] NVARCHAR(50) NOT NULL, 
    [COATTYPE] NCHAR(10) NOT NULL, 
    [COATDATE] NCHAR(10) NOT NULL
)
